nginx:
  build: ./nginx/
  ports:
    - "80:80"
  privileged: true
  links:
    - rails
  environment:
    TERM: xterm
    ADDR: 192.168.10.1
rails:
  build: ./rails/
  ports:
    - "8080:8080"
  privileged: true
  links:
    - master
  environment:
    TERM: xterm
    NAME: rabe
    MASTER_URL: mysql2://root@master:3306
    ADDR: 192.168.20.1
master:
  build: ./galera/
  expose:
    - "3306"
    - "4567"
    - "4568"
    - "4444"
  privileged: true
  environment:
    TERM: xterm
    CLUSTER_ADDR:
    DB_RWUSER: rw
    DB_RWPASS: pass
    DB_ROUSER: ro
    DB_ROPASS: pass
    ADDR: 192.168.30.1
node:
  build: ./galera/
  expose:
    - "3306"
    - "4567"
    - "4568"
    - "4444"
  privileged: true
  links:
    - "master"
  environment:
    TERM: xterm
    CLUSTER_ADDR: 192.168.30.1
    DB_ROUSER: ro
    DB_ROPASS: pass
    ADDR: 192.168.40.1
